# -*- coding: utf-8 -*-
"""
Dữ liệu sản phẩm bảo hiểm PJICO - Chủ đề: Xét điều kiện tiếp nhận bồi thường
Trích xuất từ https://www.pjico.com.vn/san-pham
"""

PRODUCTS = [
    # ================================================================
    {
        "id": "combo360_o_to",
        "name": "Combo 360° Bảo Vệ Nhà – Gia Đình – Ô tô",
        "price": "599.000đ/năm",
        "url": "https://www.pjico.com.vn/san-pham/combo-360-bao-ve-nha-gia-dinh-o-to",
        "description": (
            "Giải pháp tích hợp combo bảo hiểm 3 trong 1: Nhà ở + Tai nạn Hộ gia đình + TNDS Ô tô. "
            "Bảo vệ toàn diện ngôi nhà, gia đình và trách nhiệm dân sự ô tô."
        ),
        "coverage": [
            "Bảo hiểm Nhà ở: cháy, nổ; giông, bão, lũ lụt; ngập/tràn nước; trộm cướp; va chạm",
            "Bảo hiểm Tai nạn Hộ gia đình: tử vong/thương tật toàn bộ 100% STBH",
            "Bảo hiểm TNDS Ô tô: thiệt hại sức khỏe/tính mạng 150 triệu/năm; tài sản 100 triệu/năm",
        ],
        "exclusions": [
            "Hành vi cố ý gây thiệt hại",
            "Tài sản hư hỏng do hao mòn tự nhiên",
            "Sử dụng rượu bia, chất kích thích vượt mức cho phép khi điều khiển xe",
            "Chiến tranh, khủng bố, động đất (trừ khi có thỏa thuận bổ sung)",
        ],
        "claim_questions": [
            {
                "id": "incident_type",
                "question": "Sự cố xảy ra thuộc loại nào sau đây?",
                "options": ["Cháy, nổ", "Giông, bão, lũ lụt, ngập/tràn nước", "Trộm cướp", "Va chạm", "Tai nạn hộ gia đình", "TNDS ô tô (gây thiệt hại cho bên thứ ba)", "Khác"],
                "required": True,
            },
            {
                "id": "incident_within_coverage",
                "question": "Sự cố xảy ra có thuộc phạm vi bảo hiểm đã ghi trong hợp đồng không?",
                "options": ["Có", "Không", "Không rõ"],
                "required": True,
                "fail_if": "Không",
            },
            {
                "id": "intentional_act",
                "question": "Sự cố có phải do hành vi cố ý gây thiệt hại của chủ hợp đồng hoặc người được bảo hiểm không?",
                "options": ["Có", "Không", "Không rõ"],
                "required": True,
                "fail_if": "Có",
            },
            {
                "id": "alcohol_driving",
                "question": "Nếu sự cố liên quan đến ô tô, lái xe có sử dụng rượu bia, chất kích thích vượt mức cho phép tại thời điểm xảy ra sự cố không?",
                "options": ["Có", "Không", "Không liên quan đến ô tô"],
                "required": True,
                "fail_if": "Có",
            },
            {
                "id": "normal_wear",
                "question": "Thiệt hại có phải do tài sản hao mòn tự nhiên, không phải do sự cố bất ngờ không?",
                "options": ["Có", "Không", "Không rõ"],
                "required": True,
                "fail_if": "Có",
            },
            {
                "id": "war_terrorism",
                "question": "Sự cố có phải do chiến tranh, khủng bố, động đất (nếu không có thỏa thuận bổ sung) không?",
                "options": ["Có", "Không", "Không rõ"],
                "required": True,
                "fail_if": "Có",
            },
            {
                "id": "notification_timely",
                "question": "Anh/chị đã thông báo cho PJICO về sự cố trong thời hạn quy định (thường là 15 ngày) không?",
                "options": ["Có", "Không", "Chưa thông báo"],
                "required": True,
                "fail_if": "Không",
            },
            {
                "id": "has_documents",
                "question": "Anh/chị có đầy đủ giấy tờ, chứng từ hợp lệ liên quan đến sự cố (biên bản, ảnh, hóa đơn...) không?",
                "options": ["Có", "Không", "Đang chuẩn bị"],
                "required": True,
                "fail_if": "Không",
            },
            {
                "id": "within_policy_period",
                "question": "Sự cố xảy ra có nằm trong thời hạn bảo hiểm còn hiệu lực không?",
                "options": ["Có", "Không", "Không rõ"],
                "required": True,
                "fail_if": "Không",
            },
        ],
    },
    # ================================================================
    {
        "id": "combo360_xe_may",
        "name": "Combo 360° Bảo Vệ Nhà – Gia Đình – Xe máy",
        "price": "199.000đ/năm",
        "url": "https://www.pjico.com.vn/san-pham/combo-360-nha-gia-dinh-xe-may",
        "description": (
            "Giải pháp tích hợp combo bảo hiểm 3 trong 1: Nhà ở + Tai nạn Hộ gia đình + TNDS Xe máy."
        ),
        "coverage": [
            "Bảo hiểm Nhà ở: cháy, nổ; giông, bão, lũ lụt; ngập/tràn nước; trộm cướp; va chạm",
            "Bảo hiểm Tai nạn Hộ gia đình: tử vong/thương tật toàn bộ 100% STBH",
            "Bảo hiểm TNDS Xe máy: thiệt hại sức khỏe/tính mạng 150 triệu/năm; tài sản 50 triệu/năm",
        ],
        "exclusions": [
            "Hành vi cố ý gây thiệt hại",
            "Tài sản hư hỏng do hao mòn tự nhiên",
            "Sử dụng rượu bia, chất kích thích vượt mức cho phép khi điều khiển xe",
            "Chiến tranh, khủng bố, động đất (trừ khi có thỏa thuận bổ sung)",
        ],
        "claim_questions": [
            {
                "id": "incident_type",
                "question": "Sự cố xảy ra thuộc loại nào sau đây?",
                "options": ["Cháy, nổ", "Giông, bão, lũ lụt, ngập/tràn nước", "Trộm cướp", "Va chạm", "Tai nạn hộ gia đình", "TNDS xe máy (gây thiệt hại cho bên thứ ba)", "Khác"],
                "required": True,
            },
            {
                "id": "incident_within_coverage",
                "question": "Sự cố xảy ra có thuộc phạm vi bảo hiểm đã ghi trong hợp đồng không?",
                "options": ["Có", "Không", "Không rõ"],
                "required": True,
                "fail_if": "Không",
            },
            {
                "id": "intentional_act",
                "question": "Sự cố có phải do hành vi cố ý gây thiệt hại của chủ hợp đồng hoặc người được bảo hiểm không?",
                "options": ["Có", "Không", "Không rõ"],
                "required": True,
                "fail_if": "Có",
            },
            {
                "id": "alcohol_driving",
                "question": "Nếu sự cố liên quan đến xe máy, lái xe có sử dụng rượu bia, chất kích thích vượt mức cho phép tại thời điểm xảy ra sự cố không?",
                "options": ["Có", "Không", "Không liên quan đến xe máy"],
                "required": True,
                "fail_if": "Có",
            },
            {
                "id": "normal_wear",
                "question": "Thiệt hại có phải do tài sản hao mòn tự nhiên, không phải do sự cố bất ngờ không?",
                "options": ["Có", "Không", "Không rõ"],
                "required": True,
                "fail_if": "Có",
            },
            {
                "id": "war_terrorism",
                "question": "Sự cố có phải do chiến tranh, khủng bố, động đất (nếu không có thỏa thuận bổ sung) không?",
                "options": ["Có", "Không", "Không rõ"],
                "required": True,
                "fail_if": "Có",
            },
            {
                "id": "notification_timely",
                "question": "Anh/chị đã thông báo cho PJICO về sự cố trong thời hạn quy định (thường là 15 ngày) không?",
                "options": ["Có", "Không", "Chưa thông báo"],
                "required": True,
                "fail_if": "Không",
            },
            {
                "id": "has_documents",
                "question": "Anh/chị có đầy đủ giấy tờ, chứng từ hợp lệ liên quan đến sự cố (biên bản, ảnh, hóa đơn...) không?",
                "options": ["Có", "Không", "Đang chuẩn bị"],
                "required": True,
                "fail_if": "Không",
            },
            {
                "id": "within_policy_period",
                "question": "Sự cố xảy ra có nằm trong thời hạn bảo hiểm còn hiệu lực không?",
                "options": ["Có", "Không", "Không rõ"],
                "required": True,
                "fail_if": "Không",
            },
        ],
    },
    # ================================================================
    {
        "id": "phu_gia",
        "name": "Bảo hiểm Cháy Nổ Toàn Diện Nhà Ở PJICO Phú Gia",
        "price": "Theo quy định Nghị định 105/106",
        "url": "https://www.pjico.com.vn/san-pham/bao-hiem-chay-no-toan-dien-nha-o-pjico-phu-gia",
        "description": (
            "Phạm vi bảo hiểm rộng nhất thị trường. Bảo hiểm 6 trong 1: cháy nổ, giông bão, lốc, sét, "
            "ngập lụt, tràn đường ống, trộm cướp, động đất, va chạm."
        ),
        "coverage": [
            "Cháy, nổ; Giông, bão, lốc, sét; Ngập, lụt, tràn; Trộm, cướp; Động đất; Va chạm",
            "Hỗ trợ thuê nhà 90 ngày, dọn dẹp hiện trường, bảo hiểm ô tô/xe máy để trong nhà",
        ],
        "exclusions": [
            "Các trường hợp loại trừ theo Quy tắc sản phẩm",
        ],
        "claim_questions": [
            {
                "id": "incident_type",
                "question": "Sự cố xảy ra thuộc loại nào sau đây?",
                "options": ["Cháy, nổ", "Giông, bão, lốc, sét", "Ngập, lụt, tràn đường ống", "Trộm cướp", "Động đất", "Va chạm", "Khác"],
                "required": True,
            },
            {
                "id": "incident_within_coverage",
                "question": "Sự cố xảy ra có thuộc phạm vi bảo hiểm đã ghi trong hợp đồng không?",
                "options": ["Có", "Không", "Không rõ"],
                "required": True,
                "fail_if": "Không",
            },
            {
                "id": "intentional_act",
                "question": "Sự cố có phải do hành vi cố ý gây thiệt hại của chủ hợp đồng hoặc người được bảo hiểm không?",
                "options": ["Có", "Không", "Không rõ"],
                "required": True,
                "fail_if": "Có",
            },
            {
                "id": "normal_wear",
                "question": "Thiệt hại có phải do nhà/tài sản hao mòn tự nhiên, không phải do sự cố bất ngờ không?",
                "options": ["Có", "Không", "Không rõ"],
                "required": True,
                "fail_if": "Có",
            },
            {
                "id": "notification_timely",
                "question": "Anh/chị đã thông báo cho PJICO về sự cố trong thời hạn quy định (thường là 15 ngày) không?",
                "options": ["Có", "Không", "Chưa thông báo"],
                "required": True,
                "fail_if": "Không",
            },
            {
                "id": "has_documents",
                "question": "Anh/chị có đầy đủ giấy tờ, chứng từ hợp lệ liên quan đến sự cố (biên bản cảnh sát/chữa cháy, ảnh thiệt hại, hóa đơn...) không?",
                "options": ["Có", "Không", "Đang chuẩn bị"],
                "required": True,
                "fail_if": "Không",
            },
            {
                "id": "within_policy_period",
                "question": "Sự cố xảy ra có nằm trong thời hạn bảo hiểm còn hiệu lực không?",
                "options": ["Có", "Không", "Không rõ"],
                "required": True,
                "fail_if": "Không",
            },
            {
                "id": "ownership_valid",
                "question": "Anh/chị có giấy chứng nhận quyền sở hữu/trông coi tài sản hợp lệ tại thời điểm xảy ra sự cố không?",
                "options": ["Có", "Không", "Không rõ"],
                "required": True,
                "fail_if": "Không",
            },
        ],
    },
    # ================================================================
    {
        "id": "family_care",
        "name": "Bảo hiểm Sức Khỏe Gia Đình Family Care",
        "price": "Từ 2.000.000đ/năm - 11.200.000đ/năm",
        "url": "https://www.pjico.com.vn/san-pham/bao-hiem-suc-khoe-gia-dinh-family-care",
        "description": (
            "Giải pháp chăm sóc y tế cho hộ gia đình. Bảo lãnh viện phí tại 200+ bệnh viện. "
            "Quyền lợi lên đến 240 triệu/năm. Áp dụng 15 ngày tuổi - 65 tuổi."
        ),
        "coverage": [
            "Nội trú: 40-60 triệu/người/năm",
            "Ngoại trú: 1-3 triệu/người/năm",
            "Hạn mức bảo vệ: 80-240 triệu/năm",
            "Bảo lãnh viện phí tại 200+ bệnh viện",
        ],
        "exclusions": [
            "Bệnh có sẵn trước khi tham gia (ngoài phạm vi thỏa thuận)",
            "Trong thời gian chờ (30 ngày bệnh thông thường)",
            "Khám chữa bệnh ngoài danh mục quy định",
        ],
        "claim_questions": [
            {
                "id": "patient_age",
                "question": "Tuổi của người được bảo hiểm? (15 ngày - 65 tuổi)",
                "type": "text",
                "required": True,
            },
            {
                "id": "incident_type",
                "question": "Sự cố y tế xảy ra thuộc loại nào?",
                "options": ["Nội trú", "Ngoại trú", "Cấp cứu", "Khác"],
                "required": True,
            },
            {
                "id": "incident_within_coverage",
                "question": "Việc khám chữa bệnh có thuộc phạm vi bảo hiểm đã ghi trong hợp đồng không?",
                "options": ["Có", "Không", "Không rõ"],
                "required": True,
                "fail_if": "Không",
            },
            {
                "id": "pre_existing_condition",
                "question": "Bệnh lý đang điều trị có thuộc diện loại trừ bồi thường (bệnh có sẵn trước khi hợp đồng bảo hiểm có hiệu lực, chưa được PJICO thỏa thuận chấp nhận) không?",
                "options": ["Có", "Không", "Không rõ"],
                "required": True,
                "fail_if": "Có",
            },
            {
                "id": "within_waiting_period",
                "question": "Sự cố y tế có xảy ra trong thời gian chờ (30 ngày đầu kể từ ngày bắt đầu bảo hiểm, đối với bệnh thông thường) không?",
                "options": ["Có", "Không", "Không rõ"],
                "required": True,
                "fail_if": "Có",
            },
            {
                "id": "hospital_in_network",
                "question": "Bệnh viện/phòng khám nơi điều trị có nằm trong danh mục 200+ bệnh viện bảo lãnh viện phí của PJICO không?",
                "options": ["Có", "Không", "Không rõ"],
                "required": True,
            },
            {
                "id": "notification_timely",
                "question": "Anh/chị đã thông báo cho PJICO về việc nhập viện/điều trị trong thời hạn quy định không?",
                "options": ["Có", "Không", "Chưa thông báo"],
                "required": True,
                "fail_if": "Không",
            },
            {
                "id": "has_documents",
                "question": "Anh/chị có đầy đủ giấy tờ, chứng từ y tế hợp lệ (bệnh án, hóa đơn, đơn thuốc, kết quả xét nghiệm...) không?",
                "options": ["Có", "Không", "Đang chuẩn bị"],
                "required": True,
                "fail_if": "Không",
            },
            {
                "id": "within_policy_period",
                "question": "Sự cố y tế xảy ra có nằm trong thời hạn bảo hiểm còn hiệu lực không?",
                "options": ["Có", "Không", "Không rõ"],
                "required": True,
                "fail_if": "Không",
            },
        ],
    },
    # ================================================================
    {
        "id": "tnds_moto",
        "name": "Bảo hiểm TNDS Chủ Xe Với Lái Xe & Người Ngồi Trên Xe Mô tô/Xe Gắn Máy",
        "price": "Theo quy định",
        "url": "https://www.pjico.com.vn/san-pham/bao-hiem-trach-nhiem-cua-chu-xe-voi-lai-xe-va-nguoi-ngoi-tren-xe-mo-to-xe-gan-may",
        "description": "Bảo hiểm trách nhiệm dân sự của chủ xe đối với lái xe và người ngồi trên xe mô tô/xe gắn máy.",
        "coverage": [
            "Chi trả trách nhiệm dân sự của chủ xe với lái xe và người ngồi trên xe",
            "Phạm vi bảo hiểm rộng, nhiều lựa chọn",
        ],
        "exclusions": ["Theo quy tắc bảo hiểm cụ thể"],
        "claim_questions": [
            {
                "id": "incident_type",
                "question": "Sự cố xảy ra thuộc loại nào?",
                "options": ["Tai nạn giao thông", "Thiệt hại sức khỏe/tính mạng lái xe", "Thiệt hại sức khỏe/tính mạng người ngồi trên xe", "Thiệt hại tài sản bên thứ ba", "Khác"],
                "required": True,
            },
            {
                "id": "incident_within_coverage",
                "question": "Sự cố xảy ra có thuộc phạm vi bảo hiểm đã ghi trong hợp đồng không?",
                "options": ["Có", "Không", "Không rõ"],
                "required": True,
                "fail_if": "Không",
            },
            {
                "id": "alcohol_driving",
                "question": "Lái xe có sử dụng rượu bia, chất kích thích vượt mức cho phép tại thời điểm xảy ra sự cố không?",
                "options": ["Có", "Không", "Không rõ"],
                "required": True,
                "fail_if": "Có",
            },
            {
                "id": "intentional_act",
                "question": "Sự cố có phải do hành vi cố ý gây thiệt hại của chủ xe/lái xe không?",
                "options": ["Có", "Không", "Không rõ"],
                "required": True,
                "fail_if": "Có",
            },
            {
                "id": "law_violation",
                "question": "Lái xe có vi phạm pháp luật giao thông tại thời điểm xảy ra sự cố (không có bằng lái, vượt đèn đỏ, đi ngược chiều...) không?",
                "options": ["Có", "Không", "Không rõ"],
                "required": True,
                "fail_if": "Có",
            },
            {
                "id": "notification_timely",
                "question": "Anh/chị đã thông báo cho PJICO về sự cố trong thời hạn quy định không?",
                "options": ["Có", "Không", "Chưa thông báo"],
                "required": True,
                "fail_if": "Không",
            },
            {
                "id": "has_documents",
                "question": "Anh/chị có đầy đủ giấy tờ, chứng từ hợp lệ (biên bản cảnh sát giao thông, giấy tờ xe, hồ sơ y tế...) không?",
                "options": ["Có", "Không", "Đang chuẩn bị"],
                "required": True,
                "fail_if": "Không",
            },
            {
                "id": "within_policy_period",
                "question": "Sự cố xảy ra có nằm trong thời hạn bảo hiểm còn hiệu lực không?",
                "options": ["Có", "Không", "Không rõ"],
                "required": True,
                "fail_if": "Không",
            },
        ],
    },
    # ================================================================
    {
        "id": "gian_doan_kd",
        "name": "Bảo hiểm Gián Đoạn Kinh Doanh",
        "price": "Theo thỏa thuận",
        "url": "https://www.pjico.com.vn/san-pham/bao-hiem-gian-doan-kinh-doanh-2",
        "description": (
            "Bảo hiểm mất mát lợi nhuận gộp do giảm doanh thu hoặc gia tăng chi phí kinh doanh. "
            "Điều kiện: đã tham gia bảo hiểm cháy & rủi ro đặc biệt hoặc mọi rủi ro tài sản."
        ),
        "coverage": [
            "Bồi thường mất lợi nhuận kinh doanh và chi phí cố định khi kinh doanh bị đình trệ",
            "Chi phí chi thêm để giảm thiểu tổn thất",
        ],
        "exclusions": [
            "Chi phí không trực tiếp giảm thiểu tổn thất",
            "Các loại trừ theo quy tắc bảo hiểm tài sản gốc",
        ],
        "claim_questions": [
            {
                "id": "incident_type",
                "question": "Sự cố gây gián đoạn kinh doanh thuộc loại nào?",
                "options": ["Cháy, nổ", "Thiên tai (bão, lũ, động đất...)", "Sự cố tài sản khác", "Khác"],
                "required": True,
            },
            {
                "id": "has_property_insurance_active",
                "question": "Tại thời điểm xảy ra sự cố, anh/chị có đang có bảo hiểm cháy & rủi ro đặc biệt hoặc mọi rủi ro tài sản còn hiệu lực (điều kiện tiên quyết để bồi thường gián đoạn kinh doanh) không?",
                "options": ["Có", "Không", "Không rõ"],
                "required": True,
                "fail_if": "Không",
            },
            {
                "id": "incident_within_coverage",
                "question": "Sự cố xảy ra có thuộc phạm vi bảo hiểm đã ghi trong hợp đồng không?",
                "options": ["Có", "Không", "Không rõ"],
                "required": True,
                "fail_if": "Không",
            },
            {
                "id": "intentional_act",
                "question": "Sự cố có phải do hành vi cố ý gây thiệt hại của chủ doanh nghiệp không?",
                "options": ["Có", "Không", "Không rõ"],
                "required": True,
                "fail_if": "Có",
            },
            {
                "id": "business_legal",
                "question": "Doanh nghiệp có giấy phép kinh doanh hợp lệ tại thời điểm xảy ra sự cố không?",
                "options": ["Có", "Không", "Không rõ"],
                "required": True,
                "fail_if": "Không",
            },
            {
                "id": "notification_timely",
                "question": "Anh/chị đã thông báo cho PJICO về sự cố trong thời hạn quy định không?",
                "options": ["Có", "Không", "Chưa thông báo"],
                "required": True,
                "fail_if": "Không",
            },
            {
                "id": "has_documents",
                "question": "Anh/chị có đầy đủ giấy tờ, chứng từ hợp lệ (báo cáo tổn thất, sổ sách kế toán, hóa đơn, hợp đồng kinh tế...) không?",
                "options": ["Có", "Không", "Đang chuẩn bị"],
                "required": True,
                "fail_if": "Không",
            },
            {
                "id": "within_policy_period",
                "question": "Sự cố xảy ra có nằm trong thời hạn bảo hiểm còn hiệu lực không?",
                "options": ["Có", "Không", "Không rõ"],
                "required": True,
                "fail_if": "Không",
            },
        ],
    },
    # ================================================================
    {
        "id": "ket_hop_con_nguoi",
        "name": "Bảo hiểm Kết hợp Con người (Bảo hiểm Thân thể)",
        "price": "Theo thỏa thuận",
        "url": "https://www.pjico.com.vn/san-pham/bao-hiem-ket-hop-con-nguoi",
        "description": (
            "Gói sản phẩm dành cho doanh nghiệp, nhà máy, công ty, đơn vị tập thể mua nhằm bảo vệ "
            "quyền lợi cho công nhân trước rủi ro: tai nạn, ốm đau, bệnh tật và tử vong."
        ),
        "coverage": [
            "Điều kiện A: Tử vong do ốm đau, bệnh tật, thai sản",
            "Điều kiện B: Tử vong hoặc thương tật thân thể do tai nạn",
            "Điều kiện C: Nằm viện và/hoặc phẫu thuật do ốm đau, bệnh tật, thai sản",
        ],
        "exclusions": [
            "Người bệnh thần kinh, tâm thần, phong",
            "Người bị tàn phế hoặc thương tật vĩnh viễn từ 50% trở lên",
            "Người đang trong thời gian điều trị thương tật, bệnh tật",
            "Người ngoài độ tuổi 1-60",
        ],
        "claim_questions": [
            {
                "id": "victim_age",
                "question": "Tuổi của người được bảo hiểm?",
                "type": "text",
                "required": True,
            },
            {
                "id": "incident_type",
                "question": "Sự cố xảy ra thuộc loại nào?",
                "options": ["Tử vong do ốm đau, bệnh tật, thai sản", "Tử vong/thương tật do tai nạn", "Nằm viện/phẫu thuật do ốm đau, bệnh tật", "Khác"],
                "required": True,
            },
            {
                "id": "incident_within_coverage",
                "question": "Sự cố xảy ra có thuộc phạm vi bảo hiểm đã ghi trong hợp đồng không?",
                "options": ["Có", "Không", "Không rõ"],
                "required": True,
                "fail_if": "Không",
            },
            {
                "id": "mental_health",
                "question": "Người được bảo hiểm có bị bệnh thần kinh, tâm thần, phong (thuộc điều kiện loại trừ) không?",
                "options": ["Có", "Không", "Không rõ"],
                "required": True,
                "fail_if": "Có",
            },
            {
                "id": "disability_level",
                "question": "Người được bảo hiểm có bị tàn phế hoặc thương tật vĩnh viễn từ 50% trở lên (thuộc điều kiện loại trừ) không?",
                "options": ["Có", "Không", "Không rõ"],
                "required": True,
                "fail_if": "Có",
            },
            {
                "id": "under_treatment_before_incident",
                "question": "Người được bảo hiểm có đang trong thời gian điều trị thương tật, bệnh tật ngay trước khi sự cố xảy ra (thuộc điều kiện loại trừ bồi thường) không?",
                "options": ["Có", "Không", "Không rõ"],
                "required": True,
                "fail_if": "Có",
            },
            {
                "id": "intentional_act",
                "question": "Sự cố có phải do hành vi cố ý gây thiệt hại của người được bảo hiểm không?",
                "options": ["Có", "Không", "Không rõ"],
                "required": True,
                "fail_if": "Có",
            },
            {
                "id": "notification_timely",
                "question": "Anh/chị/công ty đã thông báo cho PJICO về sự cố trong thời hạn quy định không?",
                "options": ["Có", "Không", "Chưa thông báo"],
                "required": True,
                "fail_if": "Không",
            },
            {
                "id": "has_documents",
                "question": "Anh/chị có đầy đủ giấy tờ, chứng từ hợp lệ (giấy tờ y tế, biên bản tai nạn, hồ sơ bệnh án...) không?",
                "options": ["Có", "Không", "Đang chuẩn bị"],
                "required": True,
                "fail_if": "Không",
            },
            {
                "id": "within_policy_period",
                "question": "Sự cố xảy ra có nằm trong thời hạn bảo hiểm còn hiệu lực không?",
                "options": ["Có", "Không", "Không rõ"],
                "required": True,
                "fail_if": "Không",
            },
        ],
    },
    # ================================================================
    {
        "id": "ung_thu",
        "name": "Bảo hiểm Bệnh Ung Thư",
        "price": "Theo thỏa thuận",
        "url": "https://www.pjico.com.vn/san-pham/bao-hiem-benh-ung-thu",
        "description": (
            "Bảo hiểm bệnh Ung thư là sản phẩm bảo hiểm bổ trợ, mang đến sự bảo vệ và hỗ trợ tài chính kịp thời."
        ),
        "coverage": [
            "PJICO chi trả toàn bộ số tiền bảo hiểm khi có chẩn đoán đầu tiên về ung thư",
        ],
        "exclusions": ["Các loại trừ khác theo quy tắc bảo hiểm cụ thể"],
        "claim_questions": [
            {
                "id": "patient_age",
                "question": "Tuổi của người được bảo hiểm?",
                "type": "text",
                "required": True,
            },
            {
                "id": "incident_within_coverage",
                "question": "Việc chẩn đoán ung thư có thuộc phạm vi bảo hiểm đã ghi trong hợp đồng không?",
                "options": ["Có", "Không", "Không rõ"],
                "required": True,
                "fail_if": "Không",
            },
            {
                "id": "first_diagnosis",
                "question": "Đây có phải chẩn đoán đầu tiên về ung thư (không phải tái phát) không?",
                "options": ["Có", "Không", "Không rõ"],
                "required": True,
                "fail_if": "Không",
            },
            {
                "id": "diagnosis_within_policy",
                "question": "Chẩn đoán ung thư được thực hiện sau khi hợp đồng bảo hiểm có hiệu lực (không phải bệnh có sẵn trước khi tham gia) không?",
                "options": ["Có", "Không", "Không rõ"],
                "required": True,
                "fail_if": "Không",
            },
            {
                "id": "intentional_act",
                "question": "Sự cố có phải do hành vi cố ý của người được bảo hiểm không?",
                "options": ["Có", "Không", "Không rõ"],
                "required": True,
                "fail_if": "Có",
            },
            {
                "id": "notification_timely",
                "question": "Anh/chị đã thông báo cho PJICO về chẩn đoán ung thư trong thời hạn quy định không?",
                "options": ["Có", "Không", "Chưa thông báo"],
                "required": True,
                "fail_if": "Không",
            },
            {
                "id": "has_documents",
                "question": "Anh/chị có đầy đủ giấy tờ, chứng từ y tế hợp lệ (kết quả chẩn đoán, bệnh án, sinh thiết...) không?",
                "options": ["Có", "Không", "Đang chuẩn bị"],
                "required": True,
                "fail_if": "Không",
            },
            {
                "id": "within_policy_period",
                "question": "Chẩn đoán ung thư có được thực hiện trong thời hạn bảo hiểm còn hiệu lực không?",
                "options": ["Có", "Không", "Không rõ"],
                "required": True,
                "fail_if": "Không",
            },
        ],
    },
    # ================================================================
    {
        "id": "hiem_ngheo",
        "name": "Bảo hiểm Bệnh Hiểm Nghèo",
        "price": "Theo thỏa thuận",
        "url": "https://www.pjico.com.vn/san-pham/bao-hiem-benh-hiem-ngheo",
        "description": (
            "Bảo hiểm Bệnh Hiểm Nghèo - hỗ trợ tài chính dài hạn trong điều trị các bệnh hiểm nghèo."
        ),
        "coverage": [
            "PJICO chi trả toàn bộ số tiền bảo hiểm khi có chẩn đoán đầu tiên về bệnh hiểm nghèo",
            "15 bệnh hiểm nghèo: nhồi máu cơ tim, phẫu thuật động mạch vành, đột quỵ, ung thư, suy thận, cấy ghép nội tạng, đa xơ cứng, thương tật vĩnh viễn, ghép động mạch chủ, tăng huyết áp phổi, thay van tim, u não, Parkinson, bệnh gan giai đoạn cuối",
        ],
        "exclusions": ["Các loại trừ khác theo quy tắc bảo hiểm cụ thể"],
        "claim_questions": [
            {
                "id": "patient_age",
                "question": "Tuổi của người được bảo hiểm?",
                "type": "text",
                "required": True,
            },
            {
                "id": "incident_within_coverage",
                "question": "Bệnh hiểm nghèo được chẩn đoán có thuộc danh mục 15 bệnh được bảo hiểm không?",
                "options": ["Có", "Không", "Không rõ"],
                "required": True,
                "fail_if": "Không",
            },
            {
                "id": "first_diagnosis",
                "question": "Đây có phải chẩn đoán đầu tiên về bệnh hiểm nghèo (không phải tái phát) không?",
                "options": ["Có", "Không", "Không rõ"],
                "required": True,
                "fail_if": "Không",
            },
            {
                "id": "diagnosis_within_policy",
                "question": "Chẩn đoán bệnh hiểm nghèo được thực hiện sau khi hợp đồng bảo hiểm có hiệu lực (không phải bệnh có sẵn trước khi tham gia) không?",
                "options": ["Có", "Không", "Không rõ"],
                "required": True,
                "fail_if": "Không",
            },
            {
                "id": "intentional_act",
                "question": "Sự cố có phải do hành vi cố ý của người được bảo hiểm không?",
                "options": ["Có", "Không", "Không rõ"],
                "required": True,
                "fail_if": "Có",
            },
            {
                "id": "notification_timely",
                "question": "Anh/chị đã thông báo cho PJICO về chẩn đoán bệnh hiểm nghèo trong thời hạn quy định không?",
                "options": ["Có", "Không", "Chưa thông báo"],
                "required": True,
                "fail_if": "Không",
            },
            {
                "id": "has_documents",
                "question": "Anh/chị có đầy đủ giấy tờ, chứng từ y tế hợp lệ (kết quả chẩn đoán, bệnh án, xét nghiệm...) không?",
                "options": ["Có", "Không", "Đang chuẩn bị"],
                "required": True,
                "fail_if": "Không",
            },
            {
                "id": "within_policy_period",
                "question": "Chẩn đoán bệnh hiểm nghèo có được thực hiện trong thời hạn bảo hiểm còn hiệu lực không?",
                "options": ["Có", "Không", "Không rõ"],
                "required": True,
                "fail_if": "Không",
            },
        ],
    },
    # ================================================================
    {
        "id": "tai_nan_2424",
        "name": "Bảo hiểm Tai nạn Con người 24/24",
        "price": "Theo biểu phí PJICO",
        "url": "https://muabaohiempjico.com.vn/quy-tac-bao-hiem-tai-nan",
        "description": (
            "Bảo vệ con người 24 giờ/ngày, 7 ngày/tuần. Áp dụng cho công dân VN 16-70 tuổi và người nước ngoài học tập/công tác tại VN."
        ),
        "coverage": [
            "Tử vong do tai nạn: trả toàn bộ số tiền bảo hiểm",
            "Thương tật do tai nạn: trả theo bảng tỷ lệ",
            "Tử vong trong 1 năm sau tai nạn: trả phần chênh lệch",
        ],
        "exclusions": [
            "Người đang bị bệnh tâm thần",
            "Người bị tàn phế/thương tật vĩnh viễn từ 50%",
            "Vi phạm pháp luật, cố ý, rượu/bia/ma túy, đánh nhau, ngộ độc, động đất, chiến tranh",
        ],
        "claim_questions": [
            {
                "id": "victim_age",
                "question": "Tuổi của người được bảo hiểm?",
                "type": "text",
                "required": True,
            },
            {
                "id": "incident_type",
                "question": "Sự cố tai nạn xảy ra trong hoàn cảnh nào?",
                "options": ["Tai nạn giao thông", "Tai nạn lao động", "Tai nạn sinh hoạt", "Tai nạn khác"],
                "required": True,
            },
            {
                "id": "incident_within_coverage",
                "question": "Sự cố tai nạn có thuộc phạm vi bảo hiểm đã ghi trong hợp đồng không?",
                "options": ["Có", "Không", "Không rõ"],
                "required": True,
                "fail_if": "Không",
            },
            {
                "id": "mental_health",
                "question": "Người được bảo hiểm có đang bị bệnh tâm thần (thuộc điều kiện loại trừ) không?",
                "options": ["Có", "Không", "Không rõ"],
                "required": True,
                "fail_if": "Có",
            },
            {
                "id": "disability_level",
                "question": "Người được bảo hiểm có bị tàn phế/thương tật vĩnh viễn từ 50% trở lên (thuộc điều kiện loại trừ) không?",
                "options": ["Có", "Không", "Không rõ"],
                "required": True,
                "fail_if": "Có",
            },
            {
                "id": "intentional_act",
                "question": "Sự cố có phải do hành vi cố ý gây thiệt hại của người được bảo hiểm không?",
                "options": ["Có", "Không", "Không rõ"],
                "required": True,
                "fail_if": "Có",
            },
            {
                "id": "alcohol_driving",
                "question": "Người được bảo hiểm có sử dụng rượu bia, ma túy, chất kích thích tại thời điểm xảy ra tai nạn không?",
                "options": ["Có", "Không", "Không rõ"],
                "required": True,
                "fail_if": "Có",
            },
            {
                "id": "law_violation",
                "question": "Sự cố có liên quan đến vi phạm pháp luật, đánh nhau, ngộ độc không?",
                "options": ["Có", "Không", "Không rõ"],
                "required": True,
                "fail_if": "Có",
            },
            {
                "id": "war_earthquake",
                "question": "Sự cố có liên quan đến động đất, chiến tranh không?",
                "options": ["Có", "Không", "Không rõ"],
                "required": True,
                "fail_if": "Có",
            },
            {
                "id": "notification_timely",
                "question": "Anh/chị đã thông báo cho PJICO về sự cố tai nạn trong thời hạn quy định không?",
                "options": ["Có", "Không", "Chưa thông báo"],
                "required": True,
                "fail_if": "Không",
            },
            {
                "id": "has_documents",
                "question": "Anh/chị có đầy đủ giấy tờ, chứng từ hợp lệ (biên bản tai nạn, hồ sơ y tế, kết luận pháp y...) không?",
                "options": ["Có", "Không", "Đang chuẩn bị"],
                "required": True,
                "fail_if": "Không",
            },
            {
                "id": "within_policy_period",
                "question": "Sự cố tai nạn xảy ra có nằm trong thời hạn bảo hiểm còn hiệu lực không?",
                "options": ["Có", "Không", "Không rõ"],
                "required": True,
                "fail_if": "Không",
            },
        ],
    },
    # ================================================================
    {
        "id": "tai_nan_cao",
        "name": "Bảo hiểm Tai nạn Con người Mức Trách Nhiệm Cao",
        "price": "Theo thỏa thuận",
        "url": "https://www.pjico.com.vn/san-pham/bao-hiem-tai-nan-con-nguoi-muc-trach-nhiem-cao",
        "description": (
            "Lựa chọn tối ưu cho cá nhân, tổ chức muốn bảo vệ toàn diện và mạnh mẽ nhất. Mức trách nhiệm cao."
        ),
        "coverage": [
            "Chi trả thương tổn thân thể bất ngờ dẫn đến thương tật có thể gây tử vong trong 2 năm",
            "Chi trả chi phí y tế, viện phí",
            "Mức trách nhiệm cao hơn bảo hiểm tai nạn thông thường",
        ],
        "exclusions": ["Các loại trừ khác theo quy tắc bảo hiểm cụ thể"],
        "claim_questions": [
            {
                "id": "victim_age",
                "question": "Tuổi của người được bảo hiểm?",
                "type": "text",
                "required": True,
            },
            {
                "id": "incident_type",
                "question": "Sự cố tai nạn xảy ra trong hoàn cảnh nào?",
                "options": ["Tai nạn giao thông", "Tai nạn lao động", "Tai nạn sinh hoạt", "Tai nạn khác"],
                "required": True,
            },
            {
                "id": "incident_within_coverage",
                "question": "Sự cố tai nạn có thuộc phạm vi bảo hiểm đã ghi trong hợp đồng không?",
                "options": ["Có", "Không", "Không rõ"],
                "required": True,
                "fail_if": "Không",
            },
            {
                "id": "intentional_act",
                "question": "Sự cố có phải do hành vi cố ý gây thiệt hại của người được bảo hiểm không?",
                "options": ["Có", "Không", "Không rõ"],
                "required": True,
                "fail_if": "Có",
            },
            {
                "id": "alcohol_driving",
                "question": "Người được bảo hiểm có sử dụng rượu bia, chất kích thích vượt mức cho phép tại thời điểm xảy ra tai nạn không?",
                "options": ["Có", "Không", "Không rõ"],
                "required": True,
                "fail_if": "Có",
            },
            {
                "id": "law_violation",
                "question": "Sự cố có liên quan đến vi phạm pháp luật không?",
                "options": ["Có", "Không", "Không rõ"],
                "required": True,
                "fail_if": "Có",
            },
            {
                "id": "notification_timely",
                "question": "Anh/chị đã thông báo cho PJICO về sự cố tai nạn trong thời hạn quy định không?",
                "options": ["Có", "Không", "Chưa thông báo"],
                "required": True,
                "fail_if": "Không",
            },
            {
                "id": "has_documents",
                "question": "Anh/chị có đầy đủ giấy tờ, chứng từ hợp lệ (biên bản tai nạn, hồ sơ y tế, hóa đơn viện phí...) không?",
                "options": ["Có", "Không", "Đang chuẩn bị"],
                "required": True,
                "fail_if": "Không",
            },
            {
                "id": "within_policy_period",
                "question": "Sự cố tai nạn xảy ra có nằm trong thời hạn bảo hiểm còn hiệu lực không?",
                "options": ["Có", "Không", "Không rõ"],
                "required": True,
                "fail_if": "Không",
            },
        ],
    },
    # ================================================================
    {
        "id": "tai_nan_nguoi_su_dung_dien",
        "name": "Bảo hiểm Tai nạn Người sử dụng Điện",
        "price": "0,25% số tiền bảo hiểm/hộ/năm",
        "url": "https://www.pjico.com.vn",
        "description": (
            "Bảo hiểm tai nạn cho thành viên gia đình cùng hộ khẩu có hợp đồng sử dụng điện. "
            "Bảo vệ người được bảo hiểm khi bị tai nạn do ảnh hưởng trực tiếp của dòng điện. "
            "Số tiền bảo hiểm từ 5 triệu đến 100 triệu đồng/người/vụ."
        ),
        "coverage": [
            "Tử vong hoặc thương tật thân thể do ảnh hưởng trực tiếp của dòng điện tại hộ đăng ký sử dụng điện",
            "Tử vong hoặc thương tật do tai nạn điện khi cứu người, tài sản tại hộ có đăng ký sử dụng điện",
            "Tử vong trong vòng 1 năm sau tai nạn do hậu quả tai nạn đó",
        ],
        "exclusions": [
            "Hành vi cố ý gây tai nạn của người được bảo hiểm hoặc người thừa kế hợp pháp",
            "Cố ý vi phạm chế độ an toàn khi sử dụng điện",
            "Sử dụng rượu, bia, ma túy, chất kích thích",
            "Tai nạn do hậu quả gián tiếp của việc sử dụng điện (cháy, nổ do điện)",
            "Tử vong/thương tật không phải do điện gây nên",
            "Chưa đóng phí bảo hiểm khi xảy ra tai nạn (trừ khi PJICO chấp nhận bằng văn bản)",
            "Thành viên cơ sở sử dụng điện để sản xuất, kinh doanh, cung cấp dịch vụ điện",
            "Người bệnh tâm thần hoặc tàn phế nặng (trên 80%)",
            "Người đến thuê ở tại hộ có tham gia bảo hiểm",
        ],
        "claim_questions": [
            {
                "id": "incident_type",
                "question": "Sự cố tai nạn xảy ra trong hoàn cảnh nào?",
                "options": ["Bị tai nạn do ảnh hưởng trực tiếp của dòng điện tại hộ đăng ký sử dụng điện", "Bị tai nạn do dòng điện khi đang cứu người/tài sản tại hộ có đăng ký sử dụng điện", "Tai nạn khác"],
                "required": True,
            },
            {
                "id": "incident_within_coverage",
                "question": "Sự cố có thuộc phạm vi bảo hiểm (tai nạn do ảnh hưởng trực tiếp của dòng điện) không?",
                "options": ["Có", "Không", "Không rõ"],
                "required": True,
                "fail_if": "Không",
            },
            {
                "id": "intentional_act",
                "question": "Sự cố có phải do hành vi cố ý gây tai nạn của người được bảo hiểm hoặc người thừa kế hợp pháp không?",
                "options": ["Có", "Không", "Không rõ"],
                "required": True,
                "fail_if": "Có",
            },
            {
                "id": "safety_violation",
                "question": "Người được bảo hiểm có cố ý vi phạm chế độ an toàn khi sử dụng điện do cơ quan quản lý điện quy định không?",
                "options": ["Có", "Không", "Không rõ"],
                "required": True,
                "fail_if": "Có",
            },
            {
                "id": "alcohol_drugs",
                "question": "Người được bảo hiểm có sử dụng rượu, bia, ma túy, hoặc chất kích thích khác tại thời điểm xảy ra tai nạn không?",
                "options": ["Có", "Không", "Không rõ"],
                "required": True,
                "fail_if": "Có",
            },
            {
                "id": "indirect_cause",
                "question": "Tai nạn có xảy ra do hậu quả gián tiếp của việc sử dụng điện (cháy, nổ do điện) không?",
                "options": ["Có", "Không", "Không rõ"],
                "required": True,
                "fail_if": "Có",
            },
            {
                "id": "electric_cause",
                "question": "Thương tật/tử vong của người được bảo hiểm có phải do điện gây nên (không phải nguyên nhân khác) không?",
                "options": ["Có", "Không", "Không rõ"],
                "required": True,
                "fail_if": "Không",
            },
            {
                "id": "premium_paid",
                "question": "Tại thời điểm xảy ra tai nạn, người được bảo hiểm đã đóng phí bảo hiểm (hoặc có văn bản chấp thuận của PJICO) chưa?",
                "options": ["Có", "Không", "Không rõ"],
                "required": True,
                "fail_if": "Không",
            },
            {
                "id": "mental_health",
                "question": "Người được bảo hiểm có bị bệnh tâm thần hoặc tàn phế nặng (trên 80%) thuộc điều kiện không được bảo hiểm không?",
                "options": ["Có", "Không", "Không rõ"],
                "required": True,
                "fail_if": "Có",
            },
            {
                "id": "is_tenant",
                "question": "Người được bảo hiểm có phải là người đến thuê ở tại hộ có tham gia bảo hiểm (thuộc điều kiện không được bảo hiểm) không?",
                "options": ["Có", "Không", "Không rõ"],
                "required": True,
                "fail_if": "Có",
            },
            {
                "id": "notification_timely",
                "question": "Anh/chị đã thông báo cho PJICO về tai nạn và nộp hồ sơ trong vòng 30 ngày kể từ ngày điều trị khỏi hoặc tử vong không?",
                "options": ["Có", "Không", "Chưa thông báo"],
                "required": True,
                "fail_if": "Không",
            },
            {
                "id": "has_documents",
                "question": "Anh/chị có đầy đủ giấy tờ, chứng từ hợp lệ (giấy đề nghị trả tiền bảo hiểm, giấy chứng nhận bảo hiểm, biên bản tai nạn có xác nhận của chính quyền/công an, chứng từ y tế, hóa đơn, giấy chứng tử nếu tử vong...) không?",
                "options": ["Có", "Không", "Đang chuẩn bị"],
                "required": True,
                "fail_if": "Không",
            },
            {
                "id": "within_claim_period",
                "question": "Tai nạn xảy ra có trong thời hạn 1 năm kể từ ngày xảy ra tai nạn (thời hạn yêu cầu trả tiền bảo hiểm) không?",
                "options": ["Có", "Không", "Không rõ"],
                "required": True,
                "fail_if": "Không",
            },
            {
                "id": "within_policy_period",
                "question": "Sự cố tai nạn xảy ra có nằm trong thời hạn bảo hiểm còn hiệu lực không?",
                "options": ["Có", "Không", "Không rõ"],
                "required": True,
                "fail_if": "Không",
            },
        ],
    },
    # ================================================================
    {
        "id": "boi_thuong_nguoi_lao_dong",
        "name": "Bảo hiểm Bồi thường cho Người lao động",
        "price": "Theo thỏa thuận",
        "url": "https://www.pjico.com.vn",
        "description": (
            "Bảo hiểm trách nhiệm bồi thường cho người sử dụng lao động khi người lao động bị thương tật thân thể "
            "do tai nạn lao động hoặc bệnh nghề nghiệp trong thời hạn bảo hiểm."
        ),
        "coverage": [
            "Chi phí y tế (bao gồm nằm viện) theo số tiền bảo hiểm lựa chọn",
            "Lương thuần đầy đủ hàng tháng trong thời gian điều trị y tế",
            "Tử vong hoặc thương tật toàn bộ vĩnh viãn (từ 81%): 30 tháng lương",
            "Thương tật bộ phận vĩnh viãn: bồi thường theo Phụ lục tỷ lệ",
        ],
        "exclusions": [
            "Trách nhiệm theo thỏa thuận ngoài Luật Lao động",
            "Người lao động thuộc chủ thầu độc lập",
            "Người không phải 'người làm thuê' theo Luật pháp",
            "Chiến tranh, nội chiến, bạo loạn, khởi nghĩa, quân sự",
            "Vũ khí hạt nhân, ion hóa bức xạ, nhiễm chất phóng xạ",
            "Tai nạn do ảnh hưởng trực tiếp của rượu hoặc ma túy không do bác sĩ kê đơn",
            "Cố ý gây thương tích hoặc cố ý làm thương tật trầm trọng thêm",
            "Tai nạn/thương tật/bệnh nghề nghiệp xảy ra ngoài phạm vi VN",
            "Sản xuất, chế biến amiăng",
            "Đánh lộn (trừ phòng vệ tính mạng)",
        ],
        "claim_questions": [
            {
                "id": "incident_type",
                "question": "Sự cố xảy ra thuộc loại nào?",
                "options": ["Tai nạn lao động", "Bệnh nghề nghiệp", "Khác"],
                "required": True,
            },
            {
                "id": "has_labor_contract",
                "question": "Người lao động bị tai nạn có hợp đồng lao động với người được bảo hiểm (người sử dụng lao động) không?",
                "options": ["Có", "Không", "Không rõ"],
                "required": True,
                "fail_if": "Không",
            },
            {
                "id": "is_employee",
                "question": "Người bị tai nạn có phải là 'người làm thuê' theo nghĩa của Luật pháp Việt Nam (không phải chủ thầu độc lập) không?",
                "options": ["Có", "Không", "Không rõ"],
                "required": True,
                "fail_if": "Không",
            },
            {
                "id": "incident_within_coverage",
                "question": "Sự cố (tai nạn lao động hoặc bệnh nghề nghiệp) có thuộc phạm vi bảo hiểm đã ghi trong hợp đồng không?",
                "options": ["Có", "Không", "Không rõ"],
                "required": True,
                "fail_if": "Không",
            },
            {
                "id": "within_vietnam",
                "question": "Tai nạn hoặc bệnh nghề nghiệp có xảy ra trong phạm vi lãnh thổ Việt Nam không?",
                "options": ["Có", "Không", "Không rõ"],
                "required": True,
                "fail_if": "Không",
            },
            {
                "id": "intentional_act",
                "question": "Thương tật có do cố ý gây thương tích hoặc cố ý làm thương tật trầm trọng thêm không?",
                "options": ["Có", "Không", "Không rõ"],
                "required": True,
                "fail_if": "Có",
            },
            {
                "id": "alcohol_drugs",
                "question": "Tai nạn có do ảnh hưởng trực tiếp của rượu hoặc ma túy (không do bác sĩ kê đơn) gây ra không?",
                "options": ["Có", "Không", "Không rõ"],
                "required": True,
                "fail_if": "Có",
            },
            {
                "id": "war_terrorism",
                "question": "Thương tật có do chiến tranh, nội chiến, bạo loạn, khởi nghĩa, quân sự hoặc cướp chính quyền gây ra không?",
                "options": ["Có", "Không", "Không rõ"],
                "required": True,
                "fail_if": "Có",
            },
            {
                "id": "nuclear_asbestos",
                "question": "Sự cố có liên quan đến vũ khí hạt nhân, bức xạ, nhiễm chất phóng xạ hoặc sản xuất/chế biến amiăng không?",
                "options": ["Có", "Không", "Không rõ"],
                "required": True,
                "fail_if": "Có",
            },
            {
                "id": "fighting",
                "question": "Thương tật có phát sinh từ đánh lộn (trừ trường hợp phòng vệ tính mạng) không?",
                "options": ["Có", "Không", "Không rõ"],
                "required": True,
                "fail_if": "Có",
            },
            {
                "id": "outside_law_obligation",
                "question": "Trách nhiệm bồi thường có thuộc thỏa thuận ngoài Luật Lao động Việt Nam (không thuộc trách nhiệm theo Luật Lao động) không?",
                "options": ["Có", "Không", "Không rõ"],
                "required": True,
                "fail_if": "Có",
            },
            {
                "id": "notification_timely",
                "question": "Người được bảo hiểm đã thông báo đầy đủ thông tin chi tiết cho PJICO trong vòng 72 giờ kể từ khi phát hiện tai nạn không?",
                "options": ["Có", "Không", "Chưa thông báo"],
                "required": True,
                "fail_if": "Không",
            },
            {
                "id": "honest_declaration",
                "question": "Người được bảo hiểm đã khai báo đầy đủ và trung thực thông tin về tai nạn/bệnh nghề nghiệp cho PJICO không?",
                "options": ["Có", "Không", "Không rõ"],
                "required": True,
                "fail_if": "Không",
            },
            {
                "id": "has_documents",
                "question": "Anh/chị có đầy đủ giấy tờ, chứng từ hợp lệ (hợp đồng lao động, biên bản tai nạn lao động, hồ sơ y tế, sổ lương, chứng từ thanh toán...) không?",
                "options": ["Có", "Không", "Đang chuẩn bị"],
                "required": True,
                "fail_if": "Không",
            },
            {
                "id": "within_policy_period",
                "question": "Sự cố xảy ra có nằm trong thời hạn bảo hiểm còn hiệu lực không?",
                "options": ["Có", "Không", "Không rõ"],
                "required": True,
                "fail_if": "Không",
            },
        ],
    },
    # ================================================================
    {
        "id": "suc_khoe_nguoi_vay",
        "name": "Bảo hiểm Sức khỏe Người vay",
        "price": "Theo thỏa thuận",
        "url": "https://www.pjico.com.vn",
        "description": (
            "Bảo hiểm sức khỏe cho người vay tín dụng. Phạm vi: tử vong/thương tật toàn bộ vĩnh viãn do tai nạn, ốm đau/bệnh tật/thai sản, mất tích. "
            "Áp dụng cho người được bảo hiểm từ 18 tuổi trở lên."
        ),
        "coverage": [
            "Tử vong/thương tật toàn bộ vĩnh viãn do tai nạn",
            "Tử vong/thương tật toàn bộ vĩnh viãn do ốm đau, bệnh tật, thai sản",
            "Mất tích",
        ],
        "exclusions": [
            "Cố ý vi phạm pháp luật, luật giao thông",
            "Hành vi cố ý của người được bảo hiểm/người thụ hưởng",
            "Chiến tranh, nội chiến, nổi loạn, bạo động, khủng bố",
            "Ô nhiễm hóa chất, chất phóng xạ, nguyên liệu hạt nhân",
            "Thể thao nguy hiểm, thể thao chuyên nghiệp, leo núi, nhảy dù, đi săn...",
            "Hoạt động trên không (trừ hành khách có vé bay thương mại)",
            "Tự điều trị, dùng thuốc không theo chỉ định bác sĩ",
            "Rượu, bia, ma túy, chất kích thích",
            "Ngộ độc thức ăn, chất độc, khí ga",
            "HIV/AIDS",
            "Động đất, núi lửa, sóng thần",
            "Bệnh bẩm sinh, dị tật bẩm sinh",
            "Trong thời gian chờ",
            "Dịch bệnh truyền nhiễm theo tuyên bố cơ quan có thẩm quyền/WHO",
        ],
        "claim_questions": [
            {
                "id": "incident_type",
                "question": "Sự cố xảy ra thuộc loại nào?",
                "options": ["Tử vong/thương tật toàn bộ vĩnh viãn do tai nạn", "Tử vong/thương tật toàn bộ vĩnh viãn do ốm đau, bệnh tật, thai sản", "Mất tích", "Khác"],
                "required": True,
            },
            {
                "id": "incident_within_coverage",
                "question": "Sự cố có thuộc phạm vi bảo hiểm đã ghi trong hợp đồng không?",
                "options": ["Có", "Không", "Không rõ"],
                "required": True,
                "fail_if": "Không",
            },
            {
                "id": "within_policy_period",
                "question": "Sự cố xảy ra có nằm trong thời hạn bảo hiểm còn hiệu lực không?",
                "options": ["Có", "Không", "Không rõ"],
                "required": True,
                "fail_if": "Không",
            },
            {
                "id": "law_violation",
                "question": "Người được bảo hiểm có cố ý vi phạm pháp luật, vi phạm luật giao thông tại thời điểm xảy ra sự cố không?",
                "options": ["Có", "Không", "Không rõ"],
                "required": True,
                "fail_if": "Có",
            },
            {
                "id": "intentional_act",
                "question": "Sự cố có phải do hành vi cố ý của người được bảo hiểm hoặc người thụ hưởng không?",
                "options": ["Có", "Không", "Không rõ"],
                "required": True,
                "fail_if": "Có",
            },
            {
                "id": "war_terrorism",
                "question": "Sự cố có do chiến tranh, nội chiến, nổi loạn, bạo động, khủng bố gây ra không?",
                "options": ["Có", "Không", "Không rõ"],
                "required": True,
                "fail_if": "Có",
            },
            {
                "id": "dangerous_sports",
                "question": "Sự cố có xảy ra trong khi tham gia thể thao nguy hiểm, thể thao chuyên nghiệp, leo núi, nhảy dù, đi săn, hoạt động trên không (trừ hành khách bay thương mại) không?",
                "options": ["Có", "Không", "Không rõ"],
                "required": True,
                "fail_if": "Có",
            },
            {
                "id": "alcohol_drugs",
                "question": "Sự cố có do nguyên nhân trực tiếp từ việc sử dụng rượu, bia, ma túy, chất kích thích không?",
                "options": ["Có", "Không", "Không rõ"],
                "required": True,
                "fail_if": "Có",
            },
            {
                "id": "self_treatment",
                "question": "Người được bảo hiểm có tự điều trị hoặc dùng thuốc không theo chỉ định của bác sĩ không?",
                "options": ["Có", "Không", "Không rõ"],
                "required": True,
                "fail_if": "Có",
            },
            {
                "id": "hiv_aids",
                "question": "Người được bảo hiểm có bị nhiễm HIV/AIDS hoặc các bệnh liên quan đến HIV/AIDS không?",
                "options": ["Có", "Không", "Không rõ"],
                "required": True,
                "fail_if": "Có",
            },
            {
                "id": "natural_disaster",
                "question": "Sự cố có do động đất, núi lửa, sóng thần gây ra không?",
                "options": ["Có", "Không", "Không rõ"],
                "required": True,
                "fail_if": "Có",
            },
            {
                "id": "congenital_disease",
                "question": "Người được bảo hiểm có bệnh bẩm sinh hoặc dị tật bẩm sinh không?",
                "options": ["Có", "Không", "Không rõ"],
                "required": True,
                "fail_if": "Có",
            },
            {
                "id": "epidemic",
                "question": "Sự cố có liên quan đến dịch bệnh truyền nhiễm theo tuyên bố của cơ quan Nhà nước có thẩm quyền hoặc WHO không?",
                "options": ["Có", "Không", "Không rõ"],
                "required": True,
                "fail_if": "Có",
            },
            {
                "id": "within_waiting_period",
                "question": "Sự cố có xảy ra trong thời gian chờ (30 ngày đối với bệnh thông thường, 180 ngày đối với bệnh đặc biệt, bệnh có sẵn, biến chứng thai sản) không?",
                "options": ["Có", "Không", "Không rõ"],
                "required": True,
                "fail_if": "Có",
            },
            {
                "id": "notification_timely",
                "question": "Anh/chị đã thông báo cho PJICO về sự kiện bảo hiểm trong vòng 60 ngày kể từ thời điểm xảy ra sự kiện không?",
                "options": ["Có", "Không", "Chưa thông báo"],
                "required": True,
                "fail_if": "Không",
            },
            {
                "id": "claim_within_time_limit",
                "question": "Yêu cầu chi trả tiền bảo hiểm có được thực hiện trong thời hạn 1 năm kể từ ngày xảy ra sự kiện bảo hiểm không?",
                "options": ["Có", "Không", "Không rõ"],
                "required": True,
                "fail_if": "Không",
            },
            {
                "id": "has_documents",
                "question": "Anh/chị có đầy đủ giấy tờ, chứng từ hợp lệ (giấy yêu cầu chi trả, chứng từ y tế, biên bản tai nạn, hợp đồng tín dụng, trích lục khai tử, giấy xác nhận quyền thừa kế...) không?",
                "options": ["Có", "Không", "Đang chuẩn bị"],
                "required": True,
                "fail_if": "Không",
            },
        ],
    },    # ================================================================
    {
        "id": "hoc_sinh_sinh_vien",
        "name": "Bảo hiểm Học sinh, Sinh viên 24 giờ/ngày",
        "price": "Theo biểu phí PJICO",
        "url": "https://www.pjico.com.vn",
        "description": (
            "Bảo hiểm tai nạn thân thể 24/24 cho học sinh đang theo học tại các trường: nhà trẻ, mẫu giáo, phổ thông, đại học, cao đẳng, trung học chuyên nghiệp, học nghề. "
            "Bảo vệ học sinh khi bị tai nạn bất ngờ từ bên ngoài tác động lên thân thể."
        ),
        "coverage": [
            "Tử vong do tai nạn thuộc phạm vi bảo hiểm: trả toàn bộ số tiền bảo hiểm",
            "Thương tật thân thể do tai nạn: trả chi phí cấp cứu, điều trị, bồi dưỡng theo tỷ lệ",
            "Thương tật tạm thời: trả tiền bảo hiểm theo ngày điều trị",
            "Mở rộng: tai nạn khi cứu người, cứu tài sản, chống hành động phạm pháp",
        ],
        "exclusions": [
            "Cố ý gây tai nạn của người được bảo hiểm hoặc người thừa hưởng",
            "Đánh nhau do người được bảo hiểm gây ra",
            "Vi phạm nghiêm trọc pháp luật, nội quy nhà trường, luật an toàn giao thông",
            "Cảm đột ngột, trúng gió, bệnh tật, tai biến trong điều trị",
            "Ngộ độc thức ăn, đồ uống",
            "Điều trị hoặc dùng thuốc không theo chỉ dẫn cơ quan y tế",
            "Rượu, bia, ma túy, chất kích thích",
            "Trò chơi nguy hiểm: leo trèo cây, cột điện, mái nhà, pháo, trái nổ",
            "Chiến tranh",
            "Bệnh bẩm sinh, phẫu thuật thẩm mỹ, kế hoạch hoá sinh đẻ",
            "Tâm thần, phong, giang mai, lậu, HIV/AIDS, sốt rét, lao, bệnh nghề nghiệp",
            "Động đất, núi lửa, nhiễm phóng xạ",
        ],
        "claim_questions": [
            {
                "id": "incident_type",
                "question": "Sự cố tai nạn xảy ra trong hoàn cảnh nào?",
                "options": ["Tai nạn bất ngờ từ bên ngoài tác động lên thân thể", "Tai nạn khi cứu người/cứu tài sản/chống phạm pháp", "Khác"],
                "required": True,
            },
            {
                "id": "incident_within_coverage",
                "question": "Sự cố có thuộc phạm vi bảo hiểm đã ghi trong hợp đồng không?",
                "options": ["Có", "Không", "Không rõ"],
                "required": True,
                "fail_if": "Không",
            },
            {
                "id": "intentional_act",
                "question": "Sự cố có phải do hành động cố ý gây tai nạn của người được bảo hiểm hoặc người thừa hưởng không?",
                "options": ["Có", "Không", "Không rõ"],
                "required": True,
                "fail_if": "Có",
            },
            {
                "id": "fighting",
                "question": "Tai nạn có do việc đánh nhau mà người được bảo hiểm là nguyên nhân gây ra không?",
                "options": ["Có", "Không", "Không rõ"],
                "required": True,
                "fail_if": "Có",
            },
            {
                "id": "law_violation",
                "question": "Người được bảo hiểm (học sinh cấp 2 trở lên) có vi phạm nghiêm trọc pháp luật, nội quy nhà trường, luật an toàn giao thông tại thời điểm xảy ra sự cố không?",
                "options": ["Có", "Không", "Không rõ"],
                "required": True,
                "fail_if": "Có",
            },
            {
                "id": "sudden_illness",
                "question": "Sự cố có do cảm đột ngột, trúng gió, bệnh tật, hoặc tai biến trong quá trình điều trị bệnh gây ra không?",
                "options": ["Có", "Không", "Không rõ"],
                "required": True,
                "fail_if": "Có",
            },
            {
                "id": "food_poisoning",
                "question": "Sự cố có do ngộ độc thức ăn, đồ uống gây ra không?",
                "options": ["Có", "Không", "Không rõ"],
                "required": True,
                "fail_if": "Có",
            },
            {
                "id": "alcohol_drugs",
                "question": "Người được bảo hiểm có sử dụng hoặc bị ảnh hưởng của rượu, bia, ma túy, chất kích thích tại thời điểm xảy ra tai nạn không?",
                "options": ["Có", "Không", "Không rõ"],
                "required": True,
                "fail_if": "Có",
            },
            {
                "id": "dangerous_games",
                "question": "Tai nạn có do người được bảo hiểm tham gia trò chơi nguy hiểm (leo trèo cây, cột điện, mái nhà, nghịch pháo, trái nổ...) không?",
                "options": ["Có", "Không", "Không rõ"],
                "required": True,
                "fail_if": "Có",
            },
            {
                "id": "self_treatment",
                "question": "Người được bảo hiểm có điều trị hoặc sử dụng thuốc không theo chỉ dẫn của cơ quan y tế không?",
                "options": ["Có", "Không", "Không rõ"],
                "required": True,
                "fail_if": "Có",
            },
            {
                "id": "excluded_diseases",
                "question": "Người được bảo hiểm có bị tâm thần, phong, giang mai, lậu, HIV/AIDS, sốt rét, lao, bệnh nghề nghiệp hoặc bệnh bẩm sinh không?",
                "options": ["Có", "Không", "Không rõ"],
                "required": True,
                "fail_if": "Có",
            },
            {
                "id": "war_natural_disaster",
                "question": "Sự cố có liên quan đến chiến tranh hoặc động đất, núi lửa, nhiễm phóng xạ không?",
                "options": ["Có", "Không", "Không rõ"],
                "required": True,
                "fail_if": "Có",
            },
            {
                "id": "within_policy_period",
                "question": "Sự cố tai nạn xảy ra có nằm trong thời hạn bảo hiểm còn hiệu lực (1 năm kể từ khi đóng phí đầy đủ) không?",
                "options": ["Có", "Không", "Không rõ"],
                "required": True,
                "fail_if": "Không",
            },
            {
                "id": "notification_timely",
                "question": "Anh/chị đã gửi hồ sơ yêu cầu trả tiền bảo hiểm cho PJICO trong vòng 1 tháng kể từ ngày điều trị khỏi hoặc tử vong không?",
                "options": ["Có", "Không", "Chưa gửi"],
                "required": True,
                "fail_if": "Không",
            },
            {
                "id": "has_documents",
                "question": "Anh/chị có đầy đủ giấy tờ, chứng từ hợp lệ (giấy yêu cầu trả tiền bảo hiểm, giấy chứng nhận bảo hiểm, biên bản tai nạn có xác nhận của nhà trường/chính quyền/công an, chứng từ y tế, giấy chứng tử...) không?",
                "options": ["Có", "Không", "Đang chuẩn bị"],
                "required": True,
                "fail_if": "Không",
            },
        ],
    },
    # ================================================================
    {
        "id": "du_lich_trong_nuoc",
        "name": "Bảo hiểm Du lịch trong nước",
        "price": "Theo biểu phí PJICO",
        "url": "https://www.pjico.com.vn/san-pham/bao-hiem-du-lich-trong-nuoc",
        "description": (
            "Bảo hiểm du lịch trong nước PJICO - bảo vệ du khách khi tham quan, nghỉ mát, công tác trong phạm vi lãnh thổ Việt Nam. "
            "Áp dụng từ 1 đến 70 tuổi."
        ),
        "coverage": [
            "Tử vong, thương tật thân thể do tai nạn",
            "Tử vong không phải do tai nạn (không thuộc điểm loại trừ)",
            "Chi phí y tế khi ốm đau, bệnh tật phát sinh trong chuyến đi",
            "Mất, thiết hại hành lí do cháy, nổ, phương tiện chuyên chở bị đâm, va, chìm, lật đổ, rơi hoặc mất nguyên kiện hành lý ký gửi",
        ],
        "exclusions": [
            "Cố ý vi phạm pháp luật của người được bảo hiểm",
            "Hành vi cố ý gây thiệt hại của người được bảo hiểm hoặc người thụ hưởng",
            "Sử dụng rượu, bia, ma túy, chất kích thích",
            "Tham gia thể thao mạo hiểm (leo núi, lặn biển, nhảy dù...) không mua gói bổ sung",
            "Bệnh có sẵn trước khi tham gia bảo hiểm",
            "Chiến tranh, nội chiến, khủng bố",
            "Động đất, núi lửa, sóng thần",
            "HIV/AIDS, bệnh bẩm sinh, dị tật bẩm sinh",
            "Thai sản (trừ khi có thỏa thuận bổ sung)",
        ],
        "claim_questions": [
            {
                "id": "incident_type",
                "question": "Sự cố xảy ra thuộc loại nào?",
                "options": ["Tử vong/thương tật do tai nạn", "Tử vong không do tai nạn", "Ốm đau, bệnh tật trong chuyến đi", "Mất/thiết hại hành lý", "Khác"],
                "required": True,
            },
            {
                "id": "incident_within_coverage",
                "question": "Sự cố có thuộc phạm vi bảo hiểm đã ghi trong hợp đồng không?",
                "options": ["Có", "Không", "Không rõ"],
                "required": True,
                "fail_if": "Không",
            },
            {
                "id": "within_vietnam",
                "question": "Sự cố có xảy ra trong phạm vi lãnh thổ Việt Nam không?",
                "options": ["Có", "Không", "Không rõ"],
                "required": True,
                "fail_if": "Không",
            },
            {
                "id": "within_policy_period",
                "question": "Sự cố xảy ra có nằm trong thời hạn bảo hiểm còn hiệu lực (trong thời gian chuyến đi) không?",
                "options": ["Có", "Không", "Không rõ"],
                "required": True,
                "fail_if": "Không",
            },
            {
                "id": "intentional_act",
                "question": "Sự cố có phải do hành vi cố ý của người được bảo hiểm hoặc người thụ hưởng không?",
                "options": ["Có", "Không", "Không rõ"],
                "required": True,
                "fail_if": "Có",
            },
            {
                "id": "law_violation",
                "question": "Người được bảo hiểm có cố ý vi phạm pháp luật tại thời điểm xảy ra sự cố không?",
                "options": ["Có", "Không", "Không rõ"],
                "required": True,
                "fail_if": "Có",
            },
            {
                "id": "alcohol_drugs",
                "question": "Sự cố có liên quan đến việc sử dụng rượu, bia, ma túy, chất kích thích không?",
                "options": ["Có", "Không", "Không rõ"],
                "required": True,
                "fail_if": "Có",
            },
            {
                "id": "dangerous_sports",
                "question": "Sự cố có xảy ra khi tham gia thể thao mạo hiểm (leo núi, lặn biển, nhảy dù...) mà không mua gói bổ sung không?",
                "options": ["Có", "Không", "Không rõ"],
                "required": True,
                "fail_if": "Có",
            },
            {
                "id": "pre_existing_condition",
                "question": "Bệnh tật cần điều trị có phải là bệnh có sẵn trước khi tham gia bảo hiểm không?",
                "options": ["Có", "Không", "Không rõ"],
                "required": True,
                "fail_if": "Có",
            },
            {
                "id": "war_terrorism",
                "question": "Sự cố có do chiến tranh, nội chiến, khủng bố gây ra không?",
                "options": ["Có", "Không", "Không rõ"],
                "required": True,
                "fail_if": "Có",
            },
            {
                "id": "natural_disaster",
                "question": "Sự cố có do động đất, núi lửa, sóng thần gây ra không?",
                "options": ["Có", "Không", "Không rõ"],
                "required": True,
                "fail_if": "Có",
            },
            {
                "id": "excluded_diseases",
                "question": "Người được bảo hiểm có bị HIV/AIDS, bệnh bẩm sinh, dị tật bẩm sinh không?",
                "options": ["Có", "Không", "Không rõ"],
                "required": True,
                "fail_if": "Có",
            },
            {
                "id": "notification_timely",
                "question": "Anh/chị đã thông báo cho PJICO về sự cố trong thời hạn quy định không?",
                "options": ["Có", "Không", "Chưa thông báo"],
                "required": True,
                "fail_if": "Không",
            },
            {
                "id": "has_documents",
                "question": "Anh/chị có đầy đủ giấy tờ, chứng từ hợp lệ (giấy yêu cầu bồi thường, giấy chứng nhận bảo hiểm, chứng từ y tế, biên bản tai nạn, báo cáo mất hành lý...) không?",
                "options": ["Có", "Không", "Đang chuẩn bị"],
                "required": True,
                "fail_if": "Không",
            },
        ],
    },
    # ================================================================
    {
        "id": "du_lich_quoc_te",
        "name": "Bảo hiểm Du lịch quốc tế",
        "price": "Theo biểu phí PJICO (USD/EUR)",
        "url": "https://www.pjico.com.vn",
        "description": (
            "Bảo hiểm du lịch quốc tế PJICO - bảo vệ công dân VN, người nước ngoài cư trú tại VN khi đi du lịch quốc tế. "
            "Áp dụng từ 6 tuần tuổi đến 80 tuổi. Phạm vi: chi phí y tế, hỗ trợ cấp cứu, tai nạn cá nhân, hành lý, mất giấy tờ, hủy chuyến."
        ),
        "coverage": [
            "Chi phí y tế điều trị nội trú/ngoại trú, phẫu thuật, thuốc men tại nước sở tại",
            "Hỗ trợ cấp cứu: vận chuyển y tế, hồi dương, bảo lãnh viện phí",
            "Tai nạn cá nhân: tử vong/thương tật vĩnh viãn do tai nạn",
            "Hành lý tư trang: mất, hư hỏng do tai nạn, cướp, trộm cắp",
            "Hành lý chậm: mua sắm khẩn cấp khi hành lý bị thất lạc 12h+",
            "Mất giấy tờ thông hành: hồ chiếu, thị thực, vé máy bay",
            "Hủy/cắt ngắn chuyến đi do ốm đau, thương tật nghiêm trọc",
            "Chuyến đi bị trì hoãn trên 12 giờ",
        ],
        "exclusions": [
            "Chiến tranh, nội chiến, bạo loạn, khủng bố",
            "Bệnh có sẵn, bệnh bẩm sinh, HIV/AIDS, bệnh mãn tính",
            "Cố ý vi phạm pháp luật, tự sát, cố ý gây thương tích",
            "Rượu, bia, ma túy, chất kích thích không theo bác sĩ",
            "Thai sản, sinh nở",
            "Thể thao chuyên nghiệp, thể thao đối kháng, đua xe, leo núi, nhảy dù",
            "Leo trên 5000m hoặc lặn sâu hơn 20m",
            "Nghề nguy hiểm: đi biển, giàn khoan, hầm mỏ, xử lý chất nổ",
            "Phân hỡch hạt nhân, nhiễm phóng xạ",
            "Ra nước ngoài để chữa bệnh, du lịch trái lời khuyên bác sĩ",
            "Điều trị không theo bác sĩ, khám sức khỏ định kỳ",
        ],
        "claim_questions": [
            {
                "id": "incident_type",
                "question": "Sự cố xảy ra thuộc loại nào?",
                "options": ["Chi phí y tế (ốm đau/thương tật)", "Tai nạn cá nhân (tử vong/thương tật)", "Mất/hư hỏng hành lý", "Mất giấy tờ thông hành", "Hủy/cắt ngắn chuyến đi", "Chuyến đi bị trì hoãn", "Khác"],
                "required": True,
            },
            {
                "id": "incident_within_coverage",
                "question": "Sự cố có thuộc phạm vi bảo hiểm đã ghi trong hợp đồng không?",
                "options": ["Có", "Không", "Không rõ"],
                "required": True,
                "fail_if": "Không",
            },
            {
                "id": "within_policy_period",
                "question": "Sự cố xảy ra có nằm trong thời hạn bảo hiểm còn hiệu lực (trong thời gian chuyến đi, tối đa 180 ngày) không?",
                "options": ["Có", "Không", "Không rõ"],
                "required": True,
                "fail_if": "Không",
            },
            {
                "id": "intentional_act",
                "question": "Sự cố có phải do hành vi cố ý trái pháp luật, tự sát, hoặc cố ý gây thương tích của người được bảo hiểm không?",
                "options": ["Có", "Không", "Không rõ"],
                "required": True,
                "fail_if": "Có",
            },
            {
                "id": "alcohol_drugs",
                "question": "Sự cố có liên quan đến việc sử dụng rượu, bia, ma túy, chất kích thích mà không có chỉ định của bác sĩ không?",
                "options": ["Có", "Không", "Không rõ"],
                "required": True,
                "fail_if": "Có",
            },
            {
                "id": "pre_existing_condition",
                "question": "Bệnh tật cần điều trị có phải là bệnh có sẵn, bệnh mãn tính, bệnh bẩm sinh, HIV/AIDS, hoặc các bệnh loại trí không?",
                "options": ["Có", "Không", "Không rõ"],
                "required": True,
                "fail_if": "Có",
            },
            {
                "id": "pregnancy",
                "question": "Sự cố có liên quan đến việc mang thai, sinh nở không?",
                "options": ["Có", "Không", "Không rõ"],
                "required": True,
                "fail_if": "Có",
            },
            {
                "id": "dangerous_sports",
                "question": "Sự cố có xảy ra khi tham gia thể thao chuyên nghiệp, thể thao đối kháng, đua xe, leo núi/vách đá, nhảy dù, khám phá hang động, trượt tuyết không?",
                "options": ["Có", "Không", "Không rõ"],
                "required": True,
                "fail_if": "Có",
            },
            {
                "id": "high_altitude_diving",
                "question": "Sự cố có xảy ra khi leo lên trên 5000m so với mực nước biển hoặc lặn sâu hơn 20m không?",
                "options": ["Có", "Không", "Không rõ"],
                "required": True,
                "fail_if": "Có",
            },
            {
                "id": "dangerous_profession",
                "question": "Sự cố có liên quan đến nghề nguy hiểm (đi biển, giàn khoan, hầm mỏ, xử lý chất nổ/vũ khí) không?",
                "options": ["Có", "Không", "Không rõ"],
                "required": True,
                "fail_if": "Có",
            },
            {
                "id": "war_terrorism",
                "question": "Sự cố có do chiến tranh, nội chiến, bạo loạn, khủng bố gây ra không?",
                "options": ["Có", "Không", "Không rõ"],
                "required": True,
                "fail_if": "Có",
            },
            {
                "id": "nuclear_radiation",
                "question": "Sự cố có liên quan đến phân hỡch hạt nhân hoặc nhiễm phóng xạ không?",
                "options": ["Có", "Không", "Không rõ"],
                "required": True,
                "fail_if": "Có",
            },
            {
                "id": "travel_for_treatment",
                "question": "Người được bảo hiểm có ra nước ngoài vì mục đích chữa bệnh hoặc du lịch trái lời khuyên của bác sĩ không?",
                "options": ["Có", "Không", "Không rõ"],
                "required": True,
                "fail_if": "Có",
            },
            {
                "id": "notification_timely",
                "question": "Anh/chị đã thông báo cho PJICO về sự kiện bảo hiểm trong vòng 30 ngày kể từ ngày phát sinh sự kiện không?",
                "options": ["Có", "Không", "Chưa thông báo"],
                "required": True,
                "fail_if": "Không",
            },
            {
                "id": "has_documents",
                "question": "Anh/chị có đầy đủ giấy tờ, chứng từ hợp lệ (giấy yêu cầu trả tiền, giấy chứng nhận bảo hiểm, bản sao hộ chiếu, chứng từ y tế/biên bản tai nạn/báo cáo mất hành lý có xác nhận cơ quan thẩm quyền...) không?",
                "options": ["Có", "Không", "Đang chuẩn bị"],
                "required": True,
                "fail_if": "Không",
            },
        ],
    },
]


def get_product_by_id(product_id: str):
    """Trả về dict sản phẩm theo id, hoặc None."""
    for p in PRODUCTS:
        if p["id"] == product_id:
            return p
    return None


def get_product_by_keyword(text: str):
    """Tìm sản phẩm phù hợp dựa trên từ khóa trong tin nhắn khách hàng."""
    text_lower = text.lower()
    keywords = {
        "combo360_o_to": ["combo 360", "combo360", "nhà gia đình ô tô", "ô tô", "360 ô tô", "bao ve nha gia dinh o to"],
        "combo360_xe_may": ["combo 360 xe máy", "combo360 xe máy", "xe máy", "360 xe máy", "bao ve nha gia dinh xe may"],
        "phu_gia": ["phú gia", "cháy nổ", "chay no", "nhà ở", "phu gia", "nha o", "động đất", "dong dat"],
        "family_care": ["family care", "sức khỏe", "suc khoe", "khám chữa bệnh", "kham chua benh", "y tế", "y te", "nội trú", "ngoại trú", "viện phí"],
        "tnds_moto": ["tnds", "trách nhiệm dân sự", "trach nhiem dan su", "mô tô", "xe gắn máy", "mo to", "xe gan may", "lái xe"],
        "gian_doan_kd": ["gián đoạn kinh doanh", "gian doan kinh doanh", "kinh doanh", "lợi nhuận", "loi nhuan", "doanh thu"],
        "ket_hop_con_nguoi": ["kết hợp con người", "ket hop con nguoi", "thân thể", "than the", "bảo hiểm thân thể", "bao hiem than the", "con người", "con nguoi", "tai nạn con người", "tai nan con nguoi", "cong nhan", "công nhân"],
        "ung_thu": ["ung thu", "bệnh ung thư", "benh ung thu", "cancer", "ung thu"],
        "hiem_ngheo": ["hiểm nghèo", "hiem ngheo", "bệnh hiểm nghèo", "benh hiem ngheo"],
        "tai_nan_2424": ["tai nạn 24", "tai nan 24", "24/24", "tai nạn con người 24", "tai nan con nguoi 24", "tai nạn lao động", "tai nan lao dong"],
        "tai_nan_cao": ["tai nạn con người mức trách nhiệm cao", "tai nan con nguoi muc trach nhiem cao", "trách nhiệm cao", "trach nhiem cao", "mức trách nhiệm cao"],
        "tai_nan_nguoi_su_dung_dien": ["tai nạn người sử dụng điện", "tai nan nguoi su dung dien", "người sử dụng điện", "nguoi su dung dien", "tai nạn điện", "tai nan dien", "bảo hiểm điện", "bao hiem dien", "dòng điện", "dong dien"],
        "boi_thuong_nguoi_lao_dong": ["bồi thường người lao động", "boi thuong nguoi lao dong", "người lao động", "nguoi lao dong", "tai nạn lao động", "tai nan lao dong", "bệnh nghề nghiệp", "benh nghe nghiep", "bảo hiểm lao động", "bao hiem lao dong"],
        "suc_khoe_nguoi_vay": ["sức khỏe người vay", "suc khoe nguoi vay", "người vay", "nguoi vay", "bảo hiểm người vay", "bao hiem nguoi vay", "vay tín dụng", "vay tin dung"],
        "hoc_sinh_sinh_vien": ["học sinh", "hoc sinh", "sinh vien", "bảo hiểm học sinh", "bao hiem hoc sinh", "bảo hiểm sinh viên", "bao hiem sinh vien", "tai nạn học sinh", "tai nan hoc sinh", "24/24 học sinh"],
        "du_lich_trong_nuoc": ["du lịch trong nước", "du lich trong nuoc", "bảo hiểm du lịch", "bao hiem du lich", "du lịch", "du lich", "tham quan", "nghỉ mát", "nghi mat"],
        "du_lich_quoc_te": ["du lịch quốc tế", "du lich quoc te", "bảo hiểm du lịch quốc tế", "bao hiem du lich quoc te", "quốc tế", "quoc te", "nước ngoài", "nuoc ngoai"],
    }
    best_match = None
    best_score = 0
    for pid, kws in keywords.items():
        score = 0
        for kw in kws:
            if kw in text_lower:
                score += 1
        if score > best_score:
            best_score = score
            best_match = pid
    if best_match:
        return get_product_by_id(best_match)
    return None